package com.cit.it.ccs323a.sia.me.ui;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import com.cit.it.ccs323a.sia.me.constants.RequestStatus;
import com.cit.it.ccs323a.sia.me.constants.RequestType;
import com.cit.it.ccs323a.sia.me.core.Events;
import com.cit.it.ccs323a.sia.me.core.Request;
import com.cit.it.ccs323a.sia.me.core.User;
import com.cit.it.ccs323a.sia.me.db.DBRequest;

/**
 *
 * @author L13Y16W10
 */
public class MainUser extends javax.swing.JFrame {
    String previousUsername;
    int userID;
    private Request iniRequest;
    User user;
	ArrayList<Events> eventArr;
    Events events = new Events();
	String[] columnNames = {"Event Code", 
			"Event Name",
			"Event Date"} ;
	DefaultTableModel tableModel;
	JTable table;


    /**
     * Creates new form MainUser
     */
    public MainUser(User user) {
    	System.out.println("................ MainUser.java ; User ID" + user.getUserID());
    	previousUsername = user.getUserName();
    	userID = user.getUserID();
    	iniRequest = new Request();
    	iniRequest.setUserID(userID);
    	iniRequest.setRequestTypeID(RequestType.TO_ORGANIZER);
    	this.user = user;
        initComponents(this.user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(User user) {

        jPanel2 = new javax.swing.JPanel();
        lblProfile = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        btnNotification = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblMessage = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblBirthdate = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblConfirmPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();     
        txtBirthdate = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtEmail= new javax.swing.JTextField();
        pwdPassword = new javax.swing.JPasswordField();
        pwdConfirmPassword = new javax.swing.JPasswordField();
        btnEdit = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        txtSearchEvent = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        //btnEvent = new javax.swing.JButton();
        btnOrganizer = new javax.swing.JButton();
        lblSearchEvent = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 110, 123));

        lblProfile.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        lblProfile.setForeground(new java.awt.Color(82, 179, 217));
        lblProfile.setText("Profile:");

        btnLogout.setBackground(new java.awt.Color(255, 102, 153));
        btnLogout.setText("Log out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnNotification.setText("Notification");
        btnNotification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotificationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProfile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNotification)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogout)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLogout)
                        .addComponent(btnNotification))
                    .addComponent(lblProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jPanel3.setBackground(new java.awt.Color(52, 73, 94));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 110, 123), 5));

        lblUsername.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(82, 179, 217));
        lblUsername.setText("Username:");

        lblName.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        lblName.setForeground(new java.awt.Color(82, 179, 217));
        lblName.setText("Name:");

        lblAge.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        lblAge.setForeground(new java.awt.Color(82, 179, 217));
        lblAge.setText("Age:");

        lblBirthdate.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        lblBirthdate.setForeground(new java.awt.Color(82, 179, 217));
        lblBirthdate.setText("Birthdate:");

        lblAddress.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(82, 179, 217));
        lblAddress.setText("Address:");
        
        lblEmail.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(82, 179, 217));
        lblEmail.setText("Email:");

        lblPassword.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(82, 179, 217));
        lblPassword.setText("Password:");
        
        lblConfirmPassword.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        lblConfirmPassword.setForeground(new java.awt.Color(82, 179, 217));
        lblConfirmPassword.setText("Confirm Password:");
        
        txtUsername.setText(user.getUserName());
        txtName.setText(user.getUserFullName());
        txtAge.setText(String.valueOf(user.getUserAge()));
        txtBirthdate.setText(user.getUserBirthdate());
        txtAddress.setText(user.getUserAddress()); 
        txtEmail.setText(user.getUserEmail());
        pwdPassword.setText(user.getUserPassword());
        pwdConfirmPassword.setText(user.getUserPassword());
        
        if(iniRequest.verifyRequestIsCreated(iniRequest)) {
			btnOrganizer.setEnabled(false);
        }
        
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        btnEdit.setText("Update Profile");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	
            	if(txtName.getText().equals("") || txtAge.getText().equals("") || txtBirthdate.getText().equals("") || txtAddress.getText().equals("") ||
            			txtEmail.getText().equals("") || txtUsername.getText().equals("") || pwdPassword.getText().equals("") || pwdConfirmPassword.getText().equals("")) {
        				lblMessage.setForeground(Color.RED);          		
            			lblMessage.setText("Please input on empty field/s.");
            	} else if(!pwdPassword.getText().equals(pwdConfirmPassword.getText())) {
        				lblMessage.setForeground(Color.RED);
            			lblMessage.setText("Password and Confirm Password doesn't match.");
            	} else {
            		System.out.println("Previous Username: " + previousUsername);
            		System.out.println("New Username: " + txtUsername.getText());
            		
            		if(txtUsername.getText().toLowerCase().equals(previousUsername.toLowerCase())) {
            			System.out.println(".............. wala niya gi usab ang iyang username");
            			btnEditActionPerformed(evt);
            		} else {
            			if(user.searchUser(txtUsername.getText())) {
                			System.out.println(".............. giusab niya ang iyang username unya existing na diay.");
	            			lblMessage.setText("Username already exists.");
	            			lblMessage.setForeground(Color.RED);           				
            			} else {
                			System.out.println(".............. unya wala raman nag exist");
	                		btnEditActionPerformed(evt);
            			}
            		}         	
            	}
            }

			private void btnEditActionPerformed(ActionEvent evt) {
		    	System.out.println("Gi click ang edit");
            	user.setUserName(txtUsername.getText());
            	user.setUserFullName(txtName.getText());
            	user.setUserAge(Integer.valueOf(txtAge.getText()));
            	user.setUserBirthdate(txtBirthdate.getText());
            	user.setUserAddress(txtAddress.getText());
            	user.setUserEmail(txtEmail.getText());
            	user.setUserPassword(pwdPassword.getText());
		    	if(user.updateUserProfile(user)) {
		    		lblMessage.setForeground(new java.awt.Color(82, 179, 217));
		    		lblMessage.setText("Profile update successful.");
            		previousUsername = txtUsername.getText();
		    	} else {
		    		lblMessage.setForeground(Color.red);
		    		lblMessage.setText("Profile update unsuccessful!!!");
		    	}				
			}
        });
        
        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsername)
                            .addComponent(lblName)
                            .addComponent(lblAddress)
                            .addComponent(lblEmail)
                            .addComponent(lblPassword)
                            .addComponent(lblConfirmPassword)
                            .addComponent(lblBirthdate)
                            .addComponent(lblAge))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtAddress)
                                .addComponent(txtEmail)
                                .addComponent(pwdPassword)
                                .addComponent(pwdConfirmPassword)
                                .addComponent(txtUsername)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(btnEdit)
                    	.addComponent(lblMessage)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBirthdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddress))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pwdConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblConfirmPassword))                
                .addGap(55, 55, 55)
                .addComponent(btnEdit)
                .addComponent(lblMessage)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(52, 73, 94));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 110, 123), 5));

        btnSearch.setText("Search");

        txtSearchEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchEventActionPerformed(evt);
            }
        });
        
       /* btnEvent.setText("Event");
        btnEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEventActionPerformed(evt);
            }
        });*/
        
        btnOrganizer.setText("Request To Organize an Event");
        btnOrganizer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	btnOrganizerActionPerformed(evt);
            }
        });
        
        setTableData();
        table = new JTable(tableModel);
		table.setPreferredSize(new Dimension (750,500));
		table.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
		
		table.addMouseListener(new java.awt.event.MouseAdapter() {
			@Override
			public void mouseClicked(java.awt.event.MouseEvent evt) {


				int row = table.rowAtPoint(evt.getPoint());
				int col = table.columnAtPoint(evt.getPoint());	
				if(row != -1) {
					String eventCode = (String) table.getValueAt(row, 0);
					EventDetails ed = new EventDetails();
					System.out.println(user.getUserID()+ "--------" + eventCode);
					ed.createAndShowGUI(user, eventCode);
					ed.setVisible(true);
				}



			}});

		
		
		JScrollPane editorScrollPane = new JScrollPane(table);
        editorScrollPane.setVerticalScrollBarPolicy(
                        JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        editorScrollPane.setHorizontalScrollBarPolicy(
        				JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        editorScrollPane.setPreferredSize(new Dimension(500, 200));
        editorScrollPane.setMinimumSize(new Dimension(500, 200));
        
        JPanel eventButtonsPanel = new JPanel(new BorderLayout());
        eventButtonsPanel.add(btnOrganizer, BorderLayout.LINE_END);
        //eventButtonsPanel.add(btnEvent, BorderLayout.LINE_END);
        
        JPanel eventsPanel = new JPanel(new FlowLayout());
        eventsPanel.add(eventButtonsPanel);
        
        
        JPanel eventPanel = new JPanel(new BorderLayout());
        eventPanel.add(editorScrollPane, BorderLayout.LINE_START);
        eventPanel.add(eventsPanel,BorderLayout.LINE_END);
        

        lblSearchEvent.setFont(new java.awt.Font("Segoe Print", 0, 25)); // NOI18N
        lblSearchEvent.setForeground(new java.awt.Color(82, 179, 217));
        lblSearchEvent.setText("New Events");
        txtSearchEvent.setVisible(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSearchEvent)
                            .addComponent(txtSearchEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(93, 93, 93))
                        //.addComponent(btnSearch)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
               // .addComponent(btnEvent)
               // .addComponent(btnOrganizer)
                .addComponent(eventPanel)
                .addGap(98, 98, 98))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblSearchEvent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(txtSearchEvent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
               // .addComponent(btnSearch)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                //.addComponent(btnEvent)
               // .addComponent(btnOrganizer)
                .addComponent(eventPanel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void btnOrganizerActionPerformed(ActionEvent evt) {
    	if(JOptionPane.showConfirmDialog(null, "Do you want to request to organize an event?", "CONFIRMATION", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
    		System.out.println("Confirm request to organize event..............");
			JOptionPane.showMessageDialog(null, "Request to organize event is sent to Admin for approval.\nCheck request status through notification.", "InfoBox: CONFIRMATION", JOptionPane.INFORMATION_MESSAGE);
			Request request = new Request();
			System.out.println("...........................................userIDRequest to Organize" + userID);
			request.setUserID(userID);
			request.setRequestTypeID(RequestType.TO_ORGANIZER);
			request.setRequestStatusID(RequestStatus.PENDING);
			try {
				request.createRequest(request);
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}

			btnOrganizer.setEnabled(false);

    	} 
    }
    
	private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        Start s = new Start();
        s.show(true);
        this.show(false);         // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnNotificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotificationActionPerformed
        //NotificationOrg n = new NotificationOrg(user);
    	/*ViewNotifications n = new ViewNotifications(user);
    	n.createAndShowGUI(true);
        n.show(true); */
    	UserNotification un = new UserNotification(user);
        this.show(false);// TODO add your handling code here:
    }//GEN-LAST:event_btnNotificationActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtSearchEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchEventActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchEventActionPerformed

   /* private void btnEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEventActionPerformed
        ViewEvents v= new ViewEvents();
        v.createAndShowGUI(user);
        this.show(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnEventActionPerformed*/

    /**
     * @param args the command line arguments
     */
    
    public void setTableData() {
    	
    	eventArr = events.getAllEventsByStatus(2);

        tableModel = new DefaultTableModel(columnNames, 0);
    	
    	for(int i = 0; i < eventArr.size(); i++) {
    		String eventCode = eventArr.get(i).getEventCode();
    		String eventName = eventArr.get(i).getEventName();
    		Date eventDate = eventArr.get(i).getEventDate();
		   		
    		Object[] rowData = {eventCode, eventName, eventDate};
    		tableModel.addRow(rowData);
    	}	        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
/*        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUser().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnLogout;
   // private javax.swing.JButton btnEvent;
    private javax.swing.JButton btnOrganizer;
    private javax.swing.JButton btnNotification;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel lblSearchEvent;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBirthdate;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblConfirmPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblProfile;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JPasswordField pwdConfirmPassword;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtSearchEvent;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBirthdate;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;

    // End of variables declaration//GEN-END:variables
}
